version: '3'

services:
    logger:
         image: logger
         ports: 
             - "8080:8080"
         volumes:
           - ./logger/logs:/data:rw
         links: 
             - "logstash:logstash"       
         depends_on: 
             - kibana    
    filebeat:
        image: canozyigit/filebeat
        
        links: 
            - "logstash:logstash"
        volumes: 
            - /var/lib/docker:/var/lib/docker:ro
            - /var/run/docker.sock:/var/run/docker.sock
            - ./logger/logs:/data:rw
              

    logstash:
         image: canozyigit/logstash
         ports: 
             - "5044:5044"
         volumes:
           - ./logger/logs:/data:rw
         links: 
              - "elasticsearch:elasticsearch"
         depends_on: 
             - elasticsearch
  
    elasticsearch:
         image: elasticsearch:6.8.7
         environment:
           - bootstrap.memory_lock=true
           - ES_JAVA_OPTS=-Xms512m -Xmx512m
           - discovery.type=single-node
           - http.cors.enabled=true
           - http.cors.allow-origin=*
         volumes:
             - ./logger/logs:/data:rw

         ports: 
             - "9200:9200"   
             - "9300:9300"

         ulimits:
           memlock:
             soft: -1
             hard: -1

    kibana:
         image: kibana:6.8.7
         environment:
            SERVER_NAME: kibana.example.org
            ELASTICSEARCH_URL: http://elasticsearch:9200
         links: 
            - "elasticsearch:elasticsearch"   
         volumes:
           - ./logger/logs:/data:rw
         ports: 
             - "5601:5601"
         depends_on: 
             - elasticsearch    
        
            